import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bugatti(props) {
  const { nodes, materials } = useGLTF("/free_bugatti_chiron.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -1.57]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <group
            position={[69.289, -95.143, 25.353]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Wheel-FL_Tire_0"].geometry}
              material={materials.Tire}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Wheel-FL_Rims_0"].geometry}
              material={materials.Rims}
            />
          </group>
          <group
            position={[66.875, -95.143, 25.353]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_rotor_FL_Caliper_0.geometry}
              material={materials.Caliper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_rotor_FL_Brake_rotor_0.geometry}
              material={materials.Brake_rotor}
            />
          </group>
          <group
            position={[69.302, 91.676, 25.433]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Wheel-BL_Tire_0"].geometry}
              material={materials.Tire}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Wheel-BL_Rims_0"].geometry}
              material={materials.Rims}
            />
          </group>
          <group
            position={[66.862, 91.676, 25.433]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_rotor_BL001_Caliper_0.geometry}
              material={materials.Caliper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_rotor_BL001_Brake_rotor_0.geometry}
              material={materials.Brake_rotor}
            />
          </group>
          <group
            position={[-69.289, -95.143, 25.353]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Wheel-FR_Tire_0"].geometry}
              material={materials.Tire}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Wheel-FR_Rims_0"].geometry}
              material={materials.Rims}
            />
          </group>
          <group
            position={[-66.875, -95.143, 25.353]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_rotor_FR_Caliper_0.geometry}
              material={materials.Caliper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_rotor_FR_Brake_rotor_0.geometry}
              material={materials.Brake_rotor}
            />
          </group>
          <group
            position={[-69.302, 91.676, 25.433]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Wheel-BR_Tire_0"].geometry}
              material={materials.Tire}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Wheel-BR_Rims_0"].geometry}
              material={materials.Rims}
            />
          </group>
          <group
            position={[-66.862, 91.676, 25.433]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_rotor_BL_Caliper_0.geometry}
              material={materials.Caliper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_rotor_BL_Brake_rotor_0.geometry}
              material={materials.Brake_rotor}
            />
          </group>
          <group
            position={[-0.047, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_Body_0.geometry}
              material={materials.Body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_Darker_Parts_0.geometry}
              material={materials.Darker_Parts}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_Carbon_0.geometry}
              material={materials.Carbon}
            />
          </group>
          <group
            position={[-0.047, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Engine_Interior_2_0.geometry}
              material={materials.Interior_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Engine_Plastic_0.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Engine_Carbon_0.geometry}
              material={materials.Carbon}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Engine_Logo_0.geometry}
              material={materials.Logo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Engine_Silver_0.geometry}
              material={materials.Silver}
            />
          </group>
          <group
            position={[0, 129.146, 51.077]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Spoiler-base-1_Steel_0"].geometry}
              material={materials.Steel}
            />
            <group position={[0.013, 0.235, 0.08]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["Spoiler-base-3_Steel_0"].geometry}
                material={materials.Steel}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.spoiler_Darker_Parts_0.geometry}
                material={materials.Darker_Parts}
                position={[-0.004, -0.235, -0.007]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Spoiler-base-2_Steel_0"].geometry}
              material={materials.Steel}
              position={[-0.038, 0, 0.037]}
            />
          </group>
          <group
            position={[-0.047, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Interior_1_Darker_0.geometry}
              material={materials.Interior_1_Darker}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Plastic_0.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Interior_2_0.geometry}
              material={materials.Interior_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Interior_1_0.geometry}
              material={materials.Interior_1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Silver_0.geometry}
              material={materials.Silver}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Buttons_0.geometry}
              material={materials.Buttons}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Interior_3_0.geometry}
              material={materials.Interior_3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Mirror_0.geometry}
              material={materials.Mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Interior_Interior-light_0"].geometry}
              material={materials["Interior-light"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Speedo_0.geometry}
              material={materials.Speedo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_seats_0.geometry}
              material={materials.seats}
            />
          </group>
          <group
            position={[26.851, -45.588, 49.328]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Steering-wheel_Silver_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Steering-wheel_Interior_1_0"].geometry}
              material={materials.Interior_1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Steering-wheel_Plastic_0"].geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Steering-wheel_Interior_3_0"].geometry}
              material={materials.Interior_3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Steering-wheel_Interior_1_Darker_0"].geometry}
              material={materials.Interior_1_Darker}
            />
          </group>
          <group
            position={[59.46, -58.518, 60.25]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Body_0"].geometry}
              material={materials.Body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Darker_Parts_0"].geometry}
              material={materials.Darker_Parts}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Silver_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Turning_lights_left_0"].geometry}
              material={materials.Turning_lights_left}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Carbon_0"].geometry}
              material={materials.Carbon}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Glass_0"].geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Mirror_0"].geometry}
              material={materials.Mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Interior_3_0"].geometry}
              material={materials.Interior_3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Windshield_0"].geometry}
              material={materials.Windshield}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Plastic_0"].geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-left_Interior_2_0"].geometry}
              material={materials.Interior_2}
            />
          </group>
          <group
            position={[-0.047, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Headlight_Headlight_glass_0.geometry}
              material={materials.Headlight_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Headlight_Glass_0.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Headlight_Headlights_0.geometry}
              material={materials.Headlights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Headlight_Turning_lights_left_0.geometry}
              material={materials.Turning_lights_left}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Headlight_Headlights-light_0"].geometry}
              material={materials["Headlights-light"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Headlight_Turning_lights_right_0.geometry}
              material={materials.Turning_lights_right}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Headlight_Headlights-Lights_0"].geometry}
              material={materials["Headlights-Lights"]}
            />
          </group>
          <group
            position={[-0.047, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Tail-light_Tail-light_holder_0"].geometry}
              material={materials["Tail-light_holder"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Tail-light_Tail-light-insides_0"].geometry}
              material={materials["Tail-light-insides"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Tail-light_Tail-light-glass_0"].geometry}
              material={materials["Tail-light-glass"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Tail-light_Tail-light-LIGHT_0"].geometry}
              material={materials["Tail-light-LIGHT"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Tail-light_Turning_lights_left_0"].geometry}
              material={materials.Turning_lights_left}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Tail-light_Tail-light-glass-turning_0"].geometry}
              material={materials["Tail-light-glass-turning"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Tail-light_Brake-lights_0"].geometry}
              material={materials["Brake-lights"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Tail-light_Reverse-light001_0"].geometry}
              material={materials["Reverse-light.001"]}
            />
          </group>
          <group
            position={[-59.553, -58.518, 60.25]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Body_0"].geometry}
              material={materials.Body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Darker_Parts_0"].geometry}
              material={materials.Darker_Parts}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Silver_0"].geometry}
              material={materials.Silver}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Turning_lights_right_0"].geometry}
              material={materials.Turning_lights_right}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Carbon_0"].geometry}
              material={materials.Carbon}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Glass_0"].geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Mirror_0"].geometry}
              material={materials.Mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Interior_3_0"].geometry}
              material={materials.Interior_3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Windshield_0"].geometry}
              material={materials.Windshield}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Plastic_0"].geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Door-right_Interior_2_0"].geometry}
              material={materials.Interior_2}
            />
          </group>
          <group
            position={[-0.047, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plastic-parts_Plastic_0"].geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plastic-parts_exhaust_0"].geometry}
              material={materials.exhaust}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plastic-parts_Vents-texture_0"].geometry}
              material={materials["Vents-texture"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plastic-parts_Carbon_0"].geometry}
              material={materials.Carbon}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Plastic-parts_Headlight-1_0"].geometry}
              material={materials["Headlight-1"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Vents_Vents-texture_0"].geometry}
            material={materials["Vents-texture"]}
            position={[-0.047, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Windshields_Windshield_0.geometry}
            material={materials.Windshield}
            position={[-0.047, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/free_bugatti_chiron.glb");